using worker;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting.Systemd;
var builder = Host.CreateApplicationBuilder(args);
//builder.Host.UseSystemd();
builder.Services.AddSingleton<ModbusServer>();
builder.Services.AddSingleton<ModbusClient>();
builder.Services.AddSingleton<PiDevicePerformanceInfo>();
builder.Services.AddHostedService<Worker>();
var host = builder.Build();
host.Run();
